language: ruby
rvm:
  - "1.9.3"
  - "2.1.5"
  - "rbx"
#   - jruby-19mode # JRuby in 1.9 mode
#   - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx
before_install:
  - sudo apt-get install libosmesa6-dev;
script: "bundle exec rake test"
