language: ruby
rvm:
  - "1.9.3"
  - "2.1.5"
  - "rbx"
#   - jruby-19mode # JRuby in 1.9 mode
#   - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx
before_install:
  - sudo apt-get install xpra xserver-xorg-video-dummy libosmesa6-dev;
before_script:
  - "xpra --xvfb=\"Xorg +extension GLX -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log\"  start :9"
script: "env DISPLAY=:9 rake test"
after_script:
  - "xpra stop :9"
  - "cat ~/.xpra/*"
